services:
  db:
    image: mariadb:10.6
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compte_db
      MYSQL_USER: userAPI
      MYSQL_PASSWORD: userAPI123
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  authentification-api:
    build: .
    container_name: authentification-api
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/compte_db
      SPRING_DATASOURCE_USERNAME: userAPI
      SPRING_DATASOURCE_PASSWORD: userAPI123
    ports:
      - "8081:8081"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: userAPI123
    ports:
      - "8082:80"

volumes:
  mariadb_data:
