server:
    port: 8081
spring:
  security:
    user:
      name: admin
      password: admin
      ignore:
        urls:
          - /swagger-ui/**
          - /api-docs/**
          - /v3/api-docs/**
          - /openapi/**
          - /swagger-resources/**
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: userAPI
    password: userAPI123
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

# Configuration Springdoc OpenAPI pour Swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Authentification API
        url: /openapi/authentification_api.yaml
